mnist:
  name: MNIST
  root: "data/raw"
  download: true
  grayscale: true
  image_size: [28, 28]
  split: {train: 0.8, test: 0.2}

fashion_mnist:
  name: FashionMNIST
  root: "data/raw"
  download: true
  grayscale: true
  image_size: [28, 28]
  split: {train: 0.8, test: 0.2}

cifar10:
  name: CIFAR10
  root: "data/raw"
  download: true
  grayscale: false
  image_size: [32, 32]
  split: {train: 0.8, test: 0.2}
